version: "3.7"

services:
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: leo
      MONGO_INITDB_DATABASE: miniautorizador
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: leo
      ME_CONFIG_MONGODB_URL: mongodb://root:leo@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  mysql_db:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: miniautorizador
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  java_app:
    container_name: java_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - mysql_db
    ports:
      - 8080:8080
    volumes:
      - ./target:/app/target
      - ./src/main/resources/application-docker.properties:/app/application-docker.properties
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/miniautorizador
      SPRING_MONGODB_HOST: mongo
      SPRING_CONFIG_LOCATION: /app/application-docker.properties